//
//  PriceTable.swift
//  MacroDime
//
//  Where a food's price comes from, and the arithmetic that turns a published
//  average ("$2.272 per dozen") into the cost of one catalogue serving.
//
//  The figures live in `SourcedPrices.swift`, generated by
//  `scripts/update_prices.py` from two public US datasets:
//
//  - BLS Average Price Data: monthly, U.S. city average, collected by the
//    Bureau of Labor Statistics for the consumer price index.
//  - USDA ERS Fruit and Vegetable Prices: retail scanner averages for one year,
//    carried forward to the BLS month with the CPI for fruits and vegetables.
//
//  Nothing here goes online. The prices are compiled into the app and change
//  only when the script is rerun and a new build ships, which is what keeps
//  the App Store answer "Data Not Collected" true: showing a price never tells
//  anyone where the user shops.
//

import Foundation

// MARK: - Source

/// Which public dataset a price came from.
enum PriceSource: Hashable, Sendable {
    /// BLS Average Price Data, U.S. city average. `item` is the series title
    /// exactly as BLS publishes it.
    case bls(series: String, item: String)
    /// USDA ERS Fruit and Vegetable Prices for `year`, adjusted to the BLS
    /// month with the CPI for fruits and vegetables.
    case ers(product: String, form: String, year: Int)

    /// Short attribution for a list row, e.g. `"BLS"`.
    var publisher: String {
        switch self {
        case .bls: "BLS"
        case .ers: "USDA ERS"
        }
    }
}

/// The unit a published price is quoted in.
enum PriceUnit: String, Hashable, Sendable {
    case pound
    case dozen
    case gallon
}

// MARK: - One sourced price

struct SourcedPrice: Hashable, Sendable {
    let foodID: String
    let source: PriceSource
    /// The month the price describes, e.g. `"August 2026"`. For an ERS price,
    /// the month it was adjusted to.
    let period: String
    /// USD per `unit`, after any CPI adjustment.
    let dollarsPerUnit: Double
    let unit: PriceUnit
    /// Share of the purchased amount that ends up in the serving: 0.64 for a
    /// banana, because the peel is paid for and not eaten; 0.65 for canned
    /// beans, because the liquid is drained; 1 when the serving is weighed as
    /// bought (dry rice, raw meat, frozen vegetables).
    let yield: Double

    /// Cost of one serving of `food`, or nil when the serving cannot be put in
    /// this price's unit (a per-dozen price for a food that is not counted, a
    /// per-gallon price for one that is weighed).
    func costPerServing(of food: FoodSnapshot) -> Double? {
        guard yield > 0, dollarsPerUnit > 0 else { return nil }
        switch unit {
        case .pound:
            return dollarsPerUnit * (food.servingGrams / yield) / PriceTable.gramsPerPound

        case .gallon:
            guard case .measured(let amount)? = ServingMeasure(parsing: food.servingDescription)?.shape,
                  amount.unit == .millilitres else { return nil }
            return dollarsPerUnit * (amount.value / yield) / PriceTable.millilitresPerGallon

        case .dozen:
            guard case .counted(let count, _, _)? = ServingMeasure(parsing: food.servingDescription)?.shape
            else { return nil }
            return dollarsPerUnit * (count / yield) / 12
        }
    }
}

// MARK: - Table

enum PriceTable {

    static let gramsPerPound = 453.59237
    static let millilitresPerGallon = 3785.411784

    /// Lookup by catalogue id. Built without trapping on a duplicate id: the
    /// table is generated, and `PriceTableTests` is where a duplicate should
    /// be reported, not a launch crash.
    static let byFoodID: [String: SourcedPrice] = Dictionary(
        entries.map { ($0.foodID, $0) },
        uniquingKeysWith: { first, _ in first }
    )

    static func entry(for foodID: String) -> SourcedPrice? { byFoodID[foodID] }

    /// `food` at its sourced average, or unchanged when it has none, including
    /// every user-created food.
    static func priced(_ food: FoodSnapshot) -> FoodSnapshot {
        guard let entry = byFoodID[food.id], let cost = entry.costPerServing(of: food) else {
            return food
        }
        return food.withCost(cost)
    }

    /// What Settings says about where prices come from.
    static var summary: PriceSummary {
        let sourced = FoodCatalog.reference.filter { food in
            entry(for: food.id)?.costPerServing(of: food) != nil
        }
        return PriceSummary(
            sourcedCount: sourced.count,
            totalCount: FoodCatalog.reference.count,
            period: latestPeriod,
            ersYear: ersYear
        )
    }
}

/// The attribution Settings shows, kept here so it can be tested.
struct PriceSummary: Hashable, Sendable {
    let sourcedCount: Int
    let totalCount: Int
    let period: String
    let ersYear: Int

    var estimatedCount: Int { totalCount - sourcedCount }

    var explanation: String {
        "Official averages come from the US Bureau of Labor Statistics (\(period)) "
            + "and USDA fruit and vegetable prices (\(ersYear), adjusted to \(period) "
            + "with the consumer price index). The other \(estimatedCount) are estimates. "
            + "Prices are built into the app and change with app updates. "
            + "MacroDime never goes online to fetch them."
    }
}
