//
//  SourcedPrices.swift
//  MacroDime
//
//  GENERATED by scripts/update_prices.py on 2026-09-26. Do not edit:
//  rerun the script. See PriceTable.swift for what the fields mean and how a
//  per unit price becomes the cost of one serving.
//
//  ERS prices are 2023 averages carried to August 2026 with CPI
//  CUUR0000SAF113 (350.175 for 2023, 367.507 now, x1.0495).
//

import Foundation

extension PriceTable {

    static let generatedOn = "2026-09-26"

    /// The newest month any price in the table describes.
    static let latestPeriod = "August 2026"

    /// The year of the USDA ERS fruit and vegetable prices.
    static let ersYear = 2023

    static let entries: [SourcedPrice] = [
        // ERS 2023 Apples (Fresh): $1.8609/lb x CPI 1.0495
        SourcedPrice(
            foodID: "apple",
            source: .ers(product: "Apples", form: "Fresh", year: 2023),
            period: "August 2026",
            dollarsPerUnit: 1.9530,
            unit: .pound,
            yield: 0.9000
        ),
        // ERS 2023 Asparagus (Fresh): $3.2125/lb x CPI 1.0495
        SourcedPrice(
            foodID: "asparagus",
            source: .ers(product: "Asparagus", form: "Fresh", year: 2023),
            period: "August 2026",
            dollarsPerUnit: 3.3715,
            unit: .pound,
            yield: 0.4938
        ),
        // ERS 2023 Avocados (Fresh): $2.2624/lb x CPI 1.0495
        SourcedPrice(
            foodID: "avocado",
            source: .ers(product: "Avocados", form: "Fresh", year: 2023),
            period: "August 2026",
            dollarsPerUnit: 2.3744,
            unit: .pound,
            yield: 0.7408
        ),
        // ERS 2023 Spinach, eaten raw (Fresh): $4.5004/lb x CPI 1.0495
        SourcedPrice(
            foodID: "baby-spinach",
            source: .ers(product: "Spinach, eaten raw", form: "Fresh", year: 2023),
            period: "August 2026",
            dollarsPerUnit: 4.7232,
            unit: .pound,
            yield: 1.0000
        ),
        // BLS APU0000711211, August 2026: $0.652 per pound
        SourcedPrice(
            foodID: "banana",
            source: .bls(series: "APU0000711211", item: "Bananas, per lb."),
            period: "August 2026",
            dollarsPerUnit: 0.6520,
            unit: .pound,
            yield: 0.6400
        ),
        // ERS 2023 Green peppers (Fresh): $1.5033/lb x CPI 1.0495
        SourcedPrice(
            foodID: "bell-pepper",
            source: .ers(product: "Green peppers", form: "Fresh", year: 2023),
            period: "August 2026",
            dollarsPerUnit: 1.5777,
            unit: .pound,
            yield: 0.8200
        ),
        // ERS 2023 Cabbage, green (Fresh): $0.8266/lb x CPI 1.0495
        SourcedPrice(
            foodID: "cabbage",
            source: .ers(product: "Cabbage, green", form: "Fresh", year: 2023),
            period: "August 2026",
            dollarsPerUnit: 0.8675,
            unit: .pound,
            yield: 0.7788
        ),
        // ERS 2023 Black beans (Canned): $1.3063/lb x CPI 1.0495
        SourcedPrice(
            foodID: "canned-black-beans",
            source: .ers(product: "Black beans", form: "Canned", year: 2023),
            period: "August 2026",
            dollarsPerUnit: 1.3710,
            unit: .pound,
            yield: 0.6500
        ),
        // ERS 2023 Carrots, raw whole (Fresh): $1.0055/lb x CPI 1.0495
        SourcedPrice(
            foodID: "carrots",
            source: .ers(product: "Carrots, raw whole", form: "Fresh", year: 2023),
            period: "August 2026",
            dollarsPerUnit: 1.0553,
            unit: .pound,
            yield: 0.8900
        ),
        // BLS APU0000710212, August 2026: $5.983 per pound
        SourcedPrice(
            foodID: "cheddar-block",
            source: .bls(series: "APU0000710212", item: "Cheddar cheese, natural, per lb."),
            period: "August 2026",
            dollarsPerUnit: 5.9830,
            unit: .pound,
            yield: 1.0000
        ),
        // BLS APU0000FF1101, August 2026: $4.173 per pound
        SourcedPrice(
            foodID: "chicken-breast",
            source: .bls(series: "APU0000FF1101", item: "Chicken breast, boneless, per lb."),
            period: "August 2026",
            dollarsPerUnit: 4.1730,
            unit: .pound,
            yield: 1.0000
        ),
        // ERS 2023 Lentils (Dried): $1.9577/lb x CPI 1.0495
        SourcedPrice(
            foodID: "dried-lentils",
            source: .ers(product: "Lentils", form: "Dried", year: 2023),
            period: "August 2026",
            dollarsPerUnit: 2.0546,
            unit: .pound,
            yield: 1.0000
        ),
        // BLS APU0000701322, August 2026: $1.374 per pound
        SourcedPrice(
            foodID: "dried-pasta",
            source: .bls(series: "APU0000701322", item: "Spaghetti and macaroni, per lb."),
            period: "August 2026",
            dollarsPerUnit: 1.3740,
            unit: .pound,
            yield: 1.0000
        ),
        // BLS APU0000708111, August 2026: $2.272 per dozen
        SourcedPrice(
            foodID: "eggs-large",
            source: .bls(series: "APU0000708111", item: "Eggs, grade A, large, per doz."),
            period: "August 2026",
            dollarsPerUnit: 2.2720,
            unit: .dozen,
            yield: 1.0000
        ),
        // ERS 2023 Blueberries (Fresh): $5.1325/lb x CPI 1.0495
        SourcedPrice(
            foodID: "fresh-blueberries",
            source: .ers(product: "Blueberries", form: "Fresh", year: 2023),
            period: "August 2026",
            dollarsPerUnit: 5.3865,
            unit: .pound,
            yield: 0.9500
        ),
        // ERS 2023 Broccoli heads (Fresh): $3.0236/lb x CPI 1.0495
        SourcedPrice(
            foodID: "fresh-broccoli",
            source: .ers(product: "Broccoli heads", form: "Fresh", year: 2023),
            period: "August 2026",
            dollarsPerUnit: 3.1732,
            unit: .pound,
            yield: 0.7800
        ),
        // ERS 2023 Berries, mixed (Frozen): $4.4484/lb x CPI 1.0495
        SourcedPrice(
            foodID: "frozen-berries",
            source: .ers(product: "Berries, mixed", form: "Frozen", year: 2023),
            period: "August 2026",
            dollarsPerUnit: 4.6686,
            unit: .pound,
            yield: 1.0000
        ),
        // ERS 2023 Broccoli (Frozen): $2.5725/lb x CPI 1.0495
        SourcedPrice(
            foodID: "frozen-broccoli",
            source: .ers(product: "Broccoli", form: "Frozen", year: 2023),
            period: "August 2026",
            dollarsPerUnit: 2.6998,
            unit: .pound,
            yield: 1.0000
        ),
        // ERS 2023 Mixed vegetables, carrots, peas, corn, and green beans (Frozen): $1.9193/lb x CPI 1.0495
        SourcedPrice(
            foodID: "frozen-mixed-vegetables",
            source: .ers(product: "Mixed vegetables, carrots, peas, corn, and green beans", form: "Frozen", year: 2023),
            period: "August 2026",
            dollarsPerUnit: 2.0143,
            unit: .pound,
            yield: 1.0000
        ),
        // BLS APU0000703112, August 2026: $6.923 per pound
        SourcedPrice(
            foodID: "ground-beef-80-20",
            source: .bls(series: "APU0000703112", item: "Ground beef, 100% beef, per lb."),
            period: "August 2026",
            dollarsPerUnit: 6.9230,
            unit: .pound,
            yield: 1.0000
        ),
        // ERS 2023 Onions (Fresh): $1.0622/lb x CPI 1.0495
        SourcedPrice(
            foodID: "onion",
            source: .ers(product: "Onions", form: "Fresh", year: 2023),
            period: "August 2026",
            dollarsPerUnit: 1.1148,
            unit: .pound,
            yield: 0.9000
        ),
        // BLS APU0000712112, August 2026: $0.976 per pound
        SourcedPrice(
            foodID: "potatoes",
            source: .bls(series: "APU0000712112", item: "Potatoes, white, per lb."),
            period: "August 2026",
            dollarsPerUnit: 0.9760,
            unit: .pound,
            yield: 1.0000
        ),
        // BLS APU0000703613, August 2026: $14.357 per pound
        SourcedPrice(
            foodID: "sirloin-steak",
            source: .bls(series: "APU0000703613", item: "Steak, sirloin, USDA Choice, boneless, per lb."),
            period: "August 2026",
            dollarsPerUnit: 14.3570,
            unit: .pound,
            yield: 1.0000
        ),
        // ERS 2023 Sweet potatoes (Fresh): $1.1646/lb x CPI 1.0495
        SourcedPrice(
            foodID: "sweet-potato",
            source: .ers(product: "Sweet potatoes", form: "Fresh", year: 2023),
            period: "August 2026",
            dollarsPerUnit: 1.2223,
            unit: .pound,
            yield: 1.0000
        ),
        // BLS APU0000701312, August 2026: $1.111 per pound
        SourcedPrice(
            foodID: "white-rice",
            source: .bls(series: "APU0000701312", item: "Rice, white, long grain, uncooked, per lb."),
            period: "August 2026",
            dollarsPerUnit: 1.1110,
            unit: .pound,
            yield: 1.0000
        ),
        // BLS APU0000709112, August 2026: $4.229 per gallon
        SourcedPrice(
            foodID: "whole-milk",
            source: .bls(series: "APU0000709112", item: "Milk, fresh, whole, fortified, per gal."),
            period: "August 2026",
            dollarsPerUnit: 4.2290,
            unit: .gallon,
            yield: 1.0000
        ),
        // BLS APU0000702212, May 2026: $2.814 per pound
        SourcedPrice(
            foodID: "whole-wheat-bread",
            source: .bls(series: "APU0000702212", item: "Bread, whole wheat, pan, per lb."),
            period: "May 2026",
            dollarsPerUnit: 2.8140,
            unit: .pound,
            yield: 1.0000
        ),
    ]
}
