/*
 * PriceTable.kt
 * MacroDime
 *
 * Where a food's price comes from, and the arithmetic that turns a published
 * average ("$2.272 per dozen") into the cost of one catalogue serving. Port of
 * MacroDime/Engine/PriceTable.swift.
 *
 * The figures live in SourcedPrices.kt, generated by scripts/update_prices.py
 * from two public US datasets (BLS Average Price Data, USDA ERS Fruit and
 * Vegetable Prices). Nothing here goes online: the prices are compiled into the
 * app and change only when a new build ships, which is what keeps the Play
 * Store answer "no data collected" true.
 */
package com.lungelo.macrodime.engine

import com.lungelo.macrodime.domain.FoodSnapshot
import com.lungelo.macrodime.domain.ServingMeasure

/** Which public dataset a price came from. */
sealed interface PriceSource {
    /** BLS Average Price Data, U.S. city average. [item] is the published series title. */
    data class Bls(val series: String, val item: String) : PriceSource

    /** USDA ERS prices for [year], adjusted to the BLS month with the CPI. */
    data class Ers(val product: String, val form: String, val year: Int) : PriceSource

    /** Short attribution for a list row. */
    val publisher: String
        get() = when (this) {
            is Bls -> "BLS"
            is Ers -> "USDA ERS"
        }

    /** The published dataset, with the link the Sources screen opens. */
    val dataset: DataSource
        get() = when (this) {
            is Bls -> DataSources.AVERAGE_PRICES
            is Ers -> DataSources.FRUIT_AND_VEGETABLE_PRICES
        }
}

/** The unit a published price is quoted in. */
enum class PriceUnit { Pound, Dozen, Gallon }

data class SourcedPrice(
    val foodId: String,
    val source: PriceSource,
    /** The month the price describes, such as `August 2026`. */
    val period: String,
    /** USD per [unit], after any CPI adjustment. */
    val dollarsPerUnit: Double,
    val unit: PriceUnit,
    /**
     * Share of the purchased amount that ends up in the serving: 0.64 for a
     * banana, because the peel is paid for and not eaten; 0.65 for canned
     * beans, because the liquid is drained; 1 when weighed as bought.
     */
    val servingYield: Double,
) {
    /**
     * Cost of one serving of [food], or null when the serving cannot be put in
     * this price's unit (a per-dozen price for a food that is not counted).
     */
    fun costPerServing(food: FoodSnapshot): Double? {
        if (servingYield <= 0 || dollarsPerUnit <= 0) return null
        return when (unit) {
            PriceUnit.Pound -> dollarsPerUnit * (food.servingGrams / servingYield) / PriceTable.GRAMS_PER_POUND

            PriceUnit.Gallon -> {
                val shape = ServingMeasure.parse(food.servingDescription)?.shape
                if (shape !is ServingMeasure.Shape.Measured || shape.amount.unit != ServingMeasure.Unit.Millilitres) {
                    return null
                }
                dollarsPerUnit * (shape.amount.value / servingYield) / PriceTable.MILLILITRES_PER_GALLON
            }

            PriceUnit.Dozen -> {
                val shape = ServingMeasure.parse(food.servingDescription)?.shape
                if (shape !is ServingMeasure.Shape.Counted) return null
                dollarsPerUnit * (shape.count / servingYield) / 12
            }
        }
    }
}

object PriceTable {

    const val GRAMS_PER_POUND = 453.59237
    const val MILLILITRES_PER_GALLON = 3785.411784

    val entries: List<SourcedPrice> get() = SourcedPrices.ENTRIES
    val latestPeriod: String get() = SourcedPrices.LATEST_PERIOD
    val ersYear: Int get() = SourcedPrices.ERS_YEAR

    /**
     * Lookup by catalogue id. Built without trapping on a duplicate: the table
     * is generated, and PriceTableTest is where a duplicate is reported, not a
     * launch crash. The first entry wins.
     */
    private val byFoodId: Map<String, SourcedPrice> by lazy {
        val map = LinkedHashMap<String, SourcedPrice>()
        for (entry in SourcedPrices.ENTRIES) map.putIfAbsent(entry.foodId, entry)
        map
    }

    fun entryFor(foodId: String): SourcedPrice? = byFoodId[foodId]

    /** [food] at its sourced average, or unchanged when it has none (every user-created food). */
    fun priced(food: FoodSnapshot): FoodSnapshot {
        val cost = byFoodId[food.id]?.costPerServing(food) ?: return food
        return food.withCost(cost)
    }

    /** The catalogue foods whose price comes from [dataset], counted the way [summary] counts them. */
    fun foodsPricedFrom(dataset: DataSource): List<FoodSnapshot> =
        FoodCatalog.reference.filter { food ->
            val entry = entryFor(food.id)
            entry != null && entry.source.dataset == dataset && entry.costPerServing(food) != null
        }

    /** What Settings says about where prices come from. */
    val summary: PriceSummary
        get() {
            val sourced = FoodCatalog.reference.count { food -> entryFor(food.id)?.costPerServing(food) != null }
            return PriceSummary(
                sourcedCount = sourced,
                totalCount = FoodCatalog.reference.size,
                period = latestPeriod,
                ersYear = ersYear,
            )
        }
}

/** The attribution Settings shows, kept here so it can be tested. */
data class PriceSummary(
    val sourcedCount: Int,
    val totalCount: Int,
    val period: String,
    val ersYear: Int,
) {
    val estimatedCount: Int get() = totalCount - sourcedCount

    val explanation: String
        get() = "Official averages come from the US Bureau of Labor Statistics ($period) " +
            "and USDA fruit and vegetable prices ($ersYear, adjusted to $period " +
            "with the consumer price index). The other $estimatedCount are estimates. " +
            "Prices are built into the app and change with app updates. " +
            "MacroDime never goes online to fetch them."
}
