/*
 * SourcedPrices.kt
 * MacroDime
 *
 * GENERATED by scripts/update_prices.py on 2026-09-26. Do not edit:
 * rerun the script. See PriceTable.kt for what the fields mean and how a per
 * unit price becomes the cost of one serving. The iOS app compiles the same
 * table from MacroDime/Engine/SourcedPrices.swift.
 *
 * ERS prices are 2023 averages carried to August 2026 with CPI
 * CUUR0000SAF113 (350.175 for 2023, 367.507 now, x1.0495).
 */
package com.lungelo.macrodime.engine

internal object SourcedPrices {

    const val GENERATED_ON = "2026-09-26"

    /** The newest month any price in the table describes. */
    const val LATEST_PERIOD = "August 2026"

    /** The year of the USDA ERS fruit and vegetable prices. */
    const val ERS_YEAR = 2023

    val ENTRIES: List<SourcedPrice> = listOf(
        // ERS 2023 Apples (Fresh): $1.8609/lb x CPI 1.0495
        SourcedPrice(
            foodId = "apple",
            source = PriceSource.Ers(product = "Apples", form = "Fresh", year = 2023),
            period = "August 2026",
            dollarsPerUnit = 1.9530,
            unit = PriceUnit.Pound,
            servingYield = 0.9000,
        ),
        // ERS 2023 Asparagus (Fresh): $3.2125/lb x CPI 1.0495
        SourcedPrice(
            foodId = "asparagus",
            source = PriceSource.Ers(product = "Asparagus", form = "Fresh", year = 2023),
            period = "August 2026",
            dollarsPerUnit = 3.3715,
            unit = PriceUnit.Pound,
            servingYield = 0.4938,
        ),
        // ERS 2023 Avocados (Fresh): $2.2624/lb x CPI 1.0495
        SourcedPrice(
            foodId = "avocado",
            source = PriceSource.Ers(product = "Avocados", form = "Fresh", year = 2023),
            period = "August 2026",
            dollarsPerUnit = 2.3744,
            unit = PriceUnit.Pound,
            servingYield = 0.7408,
        ),
        // ERS 2023 Spinach, eaten raw (Fresh): $4.5004/lb x CPI 1.0495
        SourcedPrice(
            foodId = "baby-spinach",
            source = PriceSource.Ers(product = "Spinach, eaten raw", form = "Fresh", year = 2023),
            period = "August 2026",
            dollarsPerUnit = 4.7232,
            unit = PriceUnit.Pound,
            servingYield = 1.0000,
        ),
        // BLS APU0000711211, August 2026: $0.652 per pound
        SourcedPrice(
            foodId = "banana",
            source = PriceSource.Bls(series = "APU0000711211", item = "Bananas, per lb."),
            period = "August 2026",
            dollarsPerUnit = 0.6520,
            unit = PriceUnit.Pound,
            servingYield = 0.6400,
        ),
        // ERS 2023 Green peppers (Fresh): $1.5033/lb x CPI 1.0495
        SourcedPrice(
            foodId = "bell-pepper",
            source = PriceSource.Ers(product = "Green peppers", form = "Fresh", year = 2023),
            period = "August 2026",
            dollarsPerUnit = 1.5777,
            unit = PriceUnit.Pound,
            servingYield = 0.8200,
        ),
        // ERS 2023 Cabbage, green (Fresh): $0.8266/lb x CPI 1.0495
        SourcedPrice(
            foodId = "cabbage",
            source = PriceSource.Ers(product = "Cabbage, green", form = "Fresh", year = 2023),
            period = "August 2026",
            dollarsPerUnit = 0.8675,
            unit = PriceUnit.Pound,
            servingYield = 0.7788,
        ),
        // ERS 2023 Black beans (Canned): $1.3063/lb x CPI 1.0495
        SourcedPrice(
            foodId = "canned-black-beans",
            source = PriceSource.Ers(product = "Black beans", form = "Canned", year = 2023),
            period = "August 2026",
            dollarsPerUnit = 1.3710,
            unit = PriceUnit.Pound,
            servingYield = 0.6500,
        ),
        // ERS 2023 Carrots, raw whole (Fresh): $1.0055/lb x CPI 1.0495
        SourcedPrice(
            foodId = "carrots",
            source = PriceSource.Ers(product = "Carrots, raw whole", form = "Fresh", year = 2023),
            period = "August 2026",
            dollarsPerUnit = 1.0553,
            unit = PriceUnit.Pound,
            servingYield = 0.8900,
        ),
        // BLS APU0000710212, August 2026: $5.983 per pound
        SourcedPrice(
            foodId = "cheddar-block",
            source = PriceSource.Bls(series = "APU0000710212", item = "Cheddar cheese, natural, per lb."),
            period = "August 2026",
            dollarsPerUnit = 5.9830,
            unit = PriceUnit.Pound,
            servingYield = 1.0000,
        ),
        // BLS APU0000FF1101, August 2026: $4.173 per pound
        SourcedPrice(
            foodId = "chicken-breast",
            source = PriceSource.Bls(series = "APU0000FF1101", item = "Chicken breast, boneless, per lb."),
            period = "August 2026",
            dollarsPerUnit = 4.1730,
            unit = PriceUnit.Pound,
            servingYield = 1.0000,
        ),
        // ERS 2023 Lentils (Dried): $1.9577/lb x CPI 1.0495
        SourcedPrice(
            foodId = "dried-lentils",
            source = PriceSource.Ers(product = "Lentils", form = "Dried", year = 2023),
            period = "August 2026",
            dollarsPerUnit = 2.0546,
            unit = PriceUnit.Pound,
            servingYield = 1.0000,
        ),
        // BLS APU0000701322, August 2026: $1.374 per pound
        SourcedPrice(
            foodId = "dried-pasta",
            source = PriceSource.Bls(series = "APU0000701322", item = "Spaghetti and macaroni, per lb."),
            period = "August 2026",
            dollarsPerUnit = 1.3740,
            unit = PriceUnit.Pound,
            servingYield = 1.0000,
        ),
        // BLS APU0000708111, August 2026: $2.272 per dozen
        SourcedPrice(
            foodId = "eggs-large",
            source = PriceSource.Bls(series = "APU0000708111", item = "Eggs, grade A, large, per doz."),
            period = "August 2026",
            dollarsPerUnit = 2.2720,
            unit = PriceUnit.Dozen,
            servingYield = 1.0000,
        ),
        // ERS 2023 Blueberries (Fresh): $5.1325/lb x CPI 1.0495
        SourcedPrice(
            foodId = "fresh-blueberries",
            source = PriceSource.Ers(product = "Blueberries", form = "Fresh", year = 2023),
            period = "August 2026",
            dollarsPerUnit = 5.3865,
            unit = PriceUnit.Pound,
            servingYield = 0.9500,
        ),
        // ERS 2023 Broccoli heads (Fresh): $3.0236/lb x CPI 1.0495
        SourcedPrice(
            foodId = "fresh-broccoli",
            source = PriceSource.Ers(product = "Broccoli heads", form = "Fresh", year = 2023),
            period = "August 2026",
            dollarsPerUnit = 3.1732,
            unit = PriceUnit.Pound,
            servingYield = 0.7800,
        ),
        // ERS 2023 Berries, mixed (Frozen): $4.4484/lb x CPI 1.0495
        SourcedPrice(
            foodId = "frozen-berries",
            source = PriceSource.Ers(product = "Berries, mixed", form = "Frozen", year = 2023),
            period = "August 2026",
            dollarsPerUnit = 4.6686,
            unit = PriceUnit.Pound,
            servingYield = 1.0000,
        ),
        // ERS 2023 Broccoli (Frozen): $2.5725/lb x CPI 1.0495
        SourcedPrice(
            foodId = "frozen-broccoli",
            source = PriceSource.Ers(product = "Broccoli", form = "Frozen", year = 2023),
            period = "August 2026",
            dollarsPerUnit = 2.6998,
            unit = PriceUnit.Pound,
            servingYield = 1.0000,
        ),
        // ERS 2023 Mixed vegetables, carrots, peas, corn, and green beans (Frozen): $1.9193/lb x CPI 1.0495
        SourcedPrice(
            foodId = "frozen-mixed-vegetables",
            source = PriceSource.Ers(product = "Mixed vegetables, carrots, peas, corn, and green beans", form = "Frozen", year = 2023),
            period = "August 2026",
            dollarsPerUnit = 2.0143,
            unit = PriceUnit.Pound,
            servingYield = 1.0000,
        ),
        // BLS APU0000703112, August 2026: $6.923 per pound
        SourcedPrice(
            foodId = "ground-beef-80-20",
            source = PriceSource.Bls(series = "APU0000703112", item = "Ground beef, 100% beef, per lb."),
            period = "August 2026",
            dollarsPerUnit = 6.9230,
            unit = PriceUnit.Pound,
            servingYield = 1.0000,
        ),
        // ERS 2023 Onions (Fresh): $1.0622/lb x CPI 1.0495
        SourcedPrice(
            foodId = "onion",
            source = PriceSource.Ers(product = "Onions", form = "Fresh", year = 2023),
            period = "August 2026",
            dollarsPerUnit = 1.1148,
            unit = PriceUnit.Pound,
            servingYield = 0.9000,
        ),
        // BLS APU0000712112, August 2026: $0.976 per pound
        SourcedPrice(
            foodId = "potatoes",
            source = PriceSource.Bls(series = "APU0000712112", item = "Potatoes, white, per lb."),
            period = "August 2026",
            dollarsPerUnit = 0.9760,
            unit = PriceUnit.Pound,
            servingYield = 1.0000,
        ),
        // BLS APU0000703613, August 2026: $14.357 per pound
        SourcedPrice(
            foodId = "sirloin-steak",
            source = PriceSource.Bls(series = "APU0000703613", item = "Steak, sirloin, USDA Choice, boneless, per lb."),
            period = "August 2026",
            dollarsPerUnit = 14.3570,
            unit = PriceUnit.Pound,
            servingYield = 1.0000,
        ),
        // ERS 2023 Sweet potatoes (Fresh): $1.1646/lb x CPI 1.0495
        SourcedPrice(
            foodId = "sweet-potato",
            source = PriceSource.Ers(product = "Sweet potatoes", form = "Fresh", year = 2023),
            period = "August 2026",
            dollarsPerUnit = 1.2223,
            unit = PriceUnit.Pound,
            servingYield = 1.0000,
        ),
        // BLS APU0000701312, August 2026: $1.111 per pound
        SourcedPrice(
            foodId = "white-rice",
            source = PriceSource.Bls(series = "APU0000701312", item = "Rice, white, long grain, uncooked, per lb."),
            period = "August 2026",
            dollarsPerUnit = 1.1110,
            unit = PriceUnit.Pound,
            servingYield = 1.0000,
        ),
        // BLS APU0000709112, August 2026: $4.229 per gallon
        SourcedPrice(
            foodId = "whole-milk",
            source = PriceSource.Bls(series = "APU0000709112", item = "Milk, fresh, whole, fortified, per gal."),
            period = "August 2026",
            dollarsPerUnit = 4.2290,
            unit = PriceUnit.Gallon,
            servingYield = 1.0000,
        ),
        // BLS APU0000702212, May 2026: $2.814 per pound
        SourcedPrice(
            foodId = "whole-wheat-bread",
            source = PriceSource.Bls(series = "APU0000702212", item = "Bread, whole wheat, pan, per lb."),
            period = "May 2026",
            dollarsPerUnit = 2.8140,
            unit = PriceUnit.Pound,
            servingYield = 1.0000,
        ),
    )
}
